const cardsCategory = [
  "Clothes",
  "Farm animals",
  "Food",
  "Forest animals",
  "Fruits",
  "Pets",
  "Toys",
  "Vegetables",
];

const cards = [
  [
    {
      word: "shirt",
      translation: "рубашка",
      image: "./assets/img/shirt.png",
      audioSrc: "assets/audio/shirt.mp3",
    },
    {
      word: "socks",
      translation: "носки",
      image: "./assets/img/socks.png",
      audioSrc: "./assets/audio/socks.mp3",
    },
    {
      word: "hat",
      translation: "шапка",
      image: "./assets/img/hat.png",
      audioSrc: "./assets/audio/hat.mp3",
    },
    {
      word: "dress",
      translation: "платье",
      image: "./assets/img/dress.png",
      audioSrc: "./assets/audio/dress.mp3",
    },
    {
      word: "sweater",
      translation: "свитер",
      image: "./assets/img/sweater.png",
      audioSrc: "./assets/audio/sweater.mp3",
    },
    {
      word: "pants",
      translation: "штаны",
      image: "./assets/img/pants.png",
      audioSrc: "./assets/audio/pants.mp3",
    },
    {
      word: "shorts",
      translation: "шорты",
      image: "./assets/img/shorts.png",
      audioSrc: "./assets/audio/shorts.mp3",
    },
    {
      word: "undershirt",
      translation: "майка",
      image: "./assets/img/undershirt.png",
      audioSrc: "./assets/audio/undershirt.mp3",
    },
  ],
  [
    {
      word: "pig",
      translation: "свинья",
      image: "./assets/img/pig.png",
      audioSrc: "assets/audio/pig.mp3",
    },
    {
      word: "cow",
      translation: "корова",
      image: "./assets/img/cow.png",
      audioSrc: "./assets/audio/cow.mp3",
    },
    {
      word: "hen",
      translation: "курица",
      image: "./assets/img/hen.png",
      audioSrc: "./assets/audio/hen.mp3",
    },
    {
      word: "sheep",
      translation: "овечка",
      image: "./assets/img/sheep.png",
      audioSrc: "./assets/audio/sheep.mp3",
    },
    {
      word: "goose",
      translation: "гусь",
      image: "./assets/img/goose.png",
      audioSrc: "./assets/audio/goose.mp3",
    },
    {
      word: "horse",
      translation: "лошадь",
      image: "./assets/img/horse.png",
      audioSrc: "./assets/audio/horse.mp3",
    },
    {
      word: "goat",
      translation: "коза",
      image: "./assets/img/goat.png",
      audioSrc: "./assets/audio/goat.mp3",
    },
    {
      word: "donkey",
      translation: "осел",
      image: "./assets/img/donkey.png",
      audioSrc: "./assets/audio/donkey.mp3",
    },
  ],
  [
    {
      word: "sausage",
      translation: "колбаса",
      image: "./assets/img/sausage.png",
      audioSrc: "assets/audio/sausage.mp3",
    },
    {
      word: "soup",
      translation: "суп",
      image: "./assets/img/soup.png",
      audioSrc: "./assets/audio/soup.mp3",
    },
    {
      word: "bread",
      translation: "хлеб",
      image: "./assets/img/bread.png",
      audioSrc: "./assets/audio/bread.mp3",
    },
    {
      word: "cheese",
      translation: "сыр",
      image: "./assets/img/cheese.png",
      audioSrc: "./assets/audio/cheese.mp3",
    },
    {
      word: "mushroom",
      translation: "грибы",
      image: "./assets/img/mushroom.png",
      audioSrc: "./assets/audio/mushroom.mp3",
    },
    {
      word: "fish",
      translation: "рыба",
      image: "./assets/img/fish.png",
      audioSrc: "./assets/audio/fish.mp3",
    },
    {
      word: "milk",
      translation: "молоко",
      image: "./assets/img/milk.png",
      audioSrc: "./assets/audio/milk.mp3",
    },
    {
      word: "egg",
      translation: "яйцо",
      image: "./assets/img/egg.png",
      audioSrc: "./assets/audio/egg.mp3",
    },
  ],
  [
    {
      word: "squirrel",
      translation: "белка",
      image: "./assets/img/squirrel.png",
      audioSrc: "assets/audio/squirrel.mp3",
    },
    {
      word: "wild boar",
      translation: "дикий кабан",
      image: "./assets/img/wild boar.png",
      audioSrc: "./assets/audio/wild boar.mp3",
    },
    {
      word: "hedgehog",
      translation: "ёжик",
      image: "./assets/img/hedgehog.png",
      audioSrc: "./assets/audio/hedgehog.mp3",
    },
    {
      word: "wolf",
      translation: "волк",
      image: "./assets/img/wolf.png",
      audioSrc: "./assets/audio/wolf.mp3",
    },
    {
      word: "raccoon",
      translation: "енот",
      image: "./assets/img/raccoon.png",
      audioSrc: "./assets/audio/raccoon.mp3",
    },
    {
      word: "deer",
      translation: "олень",
      image: "./assets/img/deer.png",
      audioSrc: "./assets/audio/deer.mp3",
    },
    {
      word: "fox",
      translation: "лиса",
      image: "./assets/img/fox.png",
      audioSrc: "./assets/audio/fox.mp3",
    },
    {
      word: "bear",
      translation: "медведь",
      image: "./assets/img/bear.png",
      audioSrc: "./assets/audio/bear.mp3",
    },
  ],
  [
    {
      word: "pear",
      translation: "персик",
      image: "./assets/img/pear.png",
      audioSrc: "assets/audio/pear.mp3",
    },
    {
      word: "watermelon",
      translation: "арбуз",
      image: "./assets/img/watermelon.png",
      audioSrc: "./assets/audio/watermelon.mp3",
    },
    {
      word: "orange",
      translation: "апельсин",
      image: "./assets/img/orange.png",
      audioSrc: "./assets/audio/orange.mp3",
    },
    {
      word: "apple",
      translation: "яблоко",
      image: "./assets/img/apple.png",
      audioSrc: "./assets/audio/apple.mp3",
    },
    {
      word: "banana",
      translation: "банан",
      image: "./assets/img/banana.png",
      audioSrc: "./assets/audio/banana.mp3",
    },
    {
      word: "strawberry",
      translation: "клубника",
      image: "./assets/img/strawberry.png",
      audioSrc: "./assets/audio/strawberry.mp3",
    },
    {
      word: "cherry",
      translation: "вишня",
      image: "./assets/img/cherry.png",
      audioSrc: "./assets/audio/cherry.mp3",
    },
    {
      word: "raspberry",
      translation: "малина",
      image: "./assets/img/raspberry.png",
      audioSrc: "./assets/audio/raspberry.mp3",
    },
  ],
  [
    {
      word: "aquarium",
      translation: "аквариум",
      image: "./assets/img/aquarium.png",
      audioSrc: "assets/audio/aquarium.mp3",
    },
    {
      word: "turtle",
      translation: "черепаха",
      image: "./assets/img/turtle.png",
      audioSrc: "./assets/audio/turtle.mp3",
    },
    {
      word: "parrot",
      translation: "попугай",
      image: "./assets/img/parrot.png",
      audioSrc: "./assets/audio/parrot.mp3",
    },
    {
      word: "rabbit",
      translation: "кролик",
      image: "./assets/img/rabbit.png",
      audioSrc: "./assets/audio/rabbit.mp3",
    },
    {
      word: "cavy",
      translation: "хомяк",
      image: "./assets/img/cavy.png",
      audioSrc: "./assets/audio/cavy.mp3",
    },
    {
      word: "cat",
      translation: "кот",
      image: "./assets/img/cat.png",
      audioSrc: "./assets/audio/cat.mp3",
    },
    {
      word: "dog",
      translation: "собака",
      image: "./assets/img/dog.png",
      audioSrc: "./assets/audio/dog.mp3",
    },
    {
      word: "hamster",
      translation: "морская свинка",
      image: "./assets/img/hamster.png",
      audioSrc: "./assets/audio/hamster.mp3",
    },
  ],
  [
    {
      word: "car",
      translation: "машина",
      image: "./assets/img/car.png",
      audioSrc: "assets/audio/car.mp3",
    },
    {
      word: "drum",
      translation: "барабан",
      image: "./assets/img/drum.png",
      audioSrc: "./assets/audio/drum.mp3",
    },
    {
      word: "doll",
      translation: "кукла",
      image: "./assets/img/doll.png",
      audioSrc: "./assets/audio/doll.mp3",
    },
    {
      word: "cube",
      translation: "кубик",
      image: "./assets/img/cube.png",
      audioSrc: "./assets/audio/cube.mp3",
    },
    {
      word: "whirligig",
      translation: "юла",
      image: "./assets/img/whirligig.png",
      audioSrc: "./assets/audio/whirligig.mp3",
    },
    {
      word: "puzzle",
      translation: "пазл",
      image: "./assets/img/puzzle.png",
      audioSrc: "./assets/audio/puzzle.mp3",
    },
    {
      word: "rattle",
      translation: "погремушка",
      image: "./assets/img/rattle.png",
      audioSrc: "./assets/audio/rattle.mp3",
    },
    {
      word: "ball",
      translation: "мяч",
      image: "./assets/img/ball.png",
      audioSrc: "./assets/audio/ball.mp3",
    },
  ],
  [
    {
      word: "pepper",
      translation: "перец",
      image: "./assets/img/pepper.png",
      audioSrc: "assets/audio/pepper.mp3",
    },
    {
      word: "cucumber",
      translation: "огурец",
      image: "./assets/img/cucumber.png",
      audioSrc: "./assets/audio/cucumber.mp3",
    },
    {
      word: "potato",
      translation: "картофель",
      image: "./assets/img/potato.png",
      audioSrc: "./assets/audio/potato.mp3",
    },
    {
      word: "carrot",
      translation: "морковь",
      image: "./assets/img/carrot.png",
      audioSrc: "./assets/audio/carrot.mp3",
    },
    {
      word: "corn",
      translation: "кукуруза",
      image: "./assets/img/corn.png",
      audioSrc: "./assets/audio/corn.mp3",
    },
    {
      word: "tomato",
      translation: "помидор",
      image: "./assets/img/tomato.png",
      audioSrc: "./assets/audio/tomato.mp3",
    },
    {
      word: "eggplant",
      translation: "баклажан",
      image: "./assets/img/eggplant.png",
      audioSrc: "./assets/audio/eggplant.mp3",
    },
    {
      word: "onion",
      translation: "лук",
      image: "./assets/img/onion.png",
      audioSrc: "./assets/audio/onion.mp3",
    },
  ],
];

export { cards, cardsCategory };
